/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * test openapi - version 1.0.0
 *
 * 测试交互文档
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
	"login.get_login_current_user": ["GET", "/login/current-user"],
	"login.get_login_get_menus": ["GET", "/login/get-menus"],
	"login.post_login_auth_login": ["POST", "/login/auth-login"],
	"login.get_login_logout": ["GET", "/login/logout"],
	"login.post_login_reset_password": ["POST", "/login/reset-password"],
	"workbench.get_workbench_Information": ["GET", "/c7-workbench/Information"],
	"workbench.get_workbench_profile": ["GET", "/c7-workbench/profile"],
	"workbench.post_workbench_ChangePicture": ["POST", "/c7-workbench/ChangePicture"],
	"workbench.get_workbench_courseDetail": ["GET", "/c7-workbench/courseDetail"],
	"workbench.get_workbench_courseList": ["GET", "/c7-workbench/courseList"],
	"workbench.get_workbench_MyCustomers_List": ["GET", "/c7-workbench/MyCustomers/List"],
	"workbench.get_workbench_MyCustomers_get_course": ["GET", "/c7-workbench/MyCustomers/get-cus-courses/{id}"],
	"workbench.get_workbench_MyCustomers_get_cus_details": ["GET", "/c7-workbench/MyCustomers/get-cus-details/{id}"],
	"workbench.post_workbench_homework_assign": ["POST", "/c7-workbench/homework/assign"],
	"workbench.get_workbench_homework_detail": ["GET", "/c7-workbench/homework/detail"],
	"workbench.post_workbench_homework_review": ["POST", "/c7-workbench/homework/review"],
	"workbench.get_workbench_selectclass": ["GET", "/c7-workbench/selectclass"],
	"workbench.get_workbench_selectteacher": ["GET", "/c7-workbench/selectteacher"],
	"workbench.get_workbench_monthlydata": ["GET", "/c7-workbench/monthlydata"],
	"workbench.post_workbench_RepeatCoursesArrange": ["POST", "/c7-workbench/RepeatCoursesArrange"],
	"workbench.post_workbench_FreeCoursesArrange": ["POST", "/c7-workbench/FreeCoursesArrange"],
	"workbench.get_workbench_stu_list": ["GET", "/c7-workbench/Stlist"],
	"workbench.get_workbench_stu_classRecord": ["GET", "/c7-workbench/StclassRecord"],
	"workbench.get_workbench_StuProfileDetails": ["GET", "/c7-workbench/StprofileDetails"],
	"workbench.get_workbench_StuCourseProgress": ["GET", "/c7-workbench/CourseProgress"],
	"workbench.get_workbench_StuCourseRecord": ["GET", "/c7-workbench/StuCourseRecord"],
	"workbench.get_workbench_StuStudyRecord": ["GET", "/c7-workbench/StuStudyRecord"],
	"workbench.get_workbench_CourseRecord": ["GET", "/c7/workbanch/CourseRecord"],
	"workbench.get_workbench_StudentSignIn": ["GET", "/c7-workbench/StudentSignUP"],
	"workbench.get_workbench_RegisterRecord": ["GET", "/c7-workbench/RegisterRecordDetails"],
	"workbench.get_workbench_RegisterRecord_page": ["GET", "/c7-workbench/RegisterRecordlist"],
	"workbench.post_workbench_register": ["POST", "/c7-workbench/register"],
	"workbench.get_workbench_StudentHomeworkList": ["GET", "/c7-workbench/Homeworklist"],
	"workbench.get_workbench_sign": ["GET", "/c7-workbench/sign"],
	"workbench.get_workbench_remark": ["GET", "/c7-workbench/remark"],
	"workbench.get_workbench_classroom": ["GET", "/c7-workbench/classroom"],
	"workbench.post_workbench_add_student_info": ["POST", "/c7-workbench/add_student/info"],
	"workbench.get_workbench_StudentSignInUp": ["GET", "/c7/workbanch/StudentSignInUp"],
	"workbench.get_workbench_RegisterRecordDetails": ["GET", "/c7-workbench/RegistRecordDetails"],
	"workbench.get_workbench_RegisterRecordList": ["GET", "/c7-workbench/RegistRecordList"],
	"class.get_class_byname": ["GET", "/c7-class/class/classid"],
	"class.get_class": ["GET", "/c7-class/class"],
	"class.get_class_GetClassStudentCourseList": ["GET", "/c7-class/class/GetClassStudentCourseList"],
	"class.get_class_GetClassStudentDetails": ["GET", "/c7-class/class/GetClassStudentDetails"],
	"class.get_class_GetClassStudentList": ["GET", "/c7-class/class/GetClassStudentList"],
	"course.get_course_get_common_datetime": ["GET", "/course/get-common-datetime"],
	"course.get_course_record_comment_cs_comment_list": ["GET", "/course/record-comment/cs-comment-list"],
	"course.put_course_record_comment_comment_stu": ["PUT", "/course/record-comment/comment-stu"],
	"course.get_course_record_name_get_detail_cs": ["GET", "/course/record-name/get-detail-cs"],
	"course.get_course_record_name_get_cs_stu_list": ["GET", "/course/record-name/get-cs-stu-list"],
	"course.put_course_record_name_set_status": ["PUT", "/course/record-name/set-status"],
	"course.get_course_record_name_stu_list": ["GET", "/course/record-name/stu-list"],
	"course.get_course_record_name_stu_course_list": ["GET", "/course/record-name/stu-course-list"],
	"course.post_course_record_name_stu_add_to_cs": ["POST", "/course/record-name/stu-add-to-cs"],
	"article.get_article": ["GET", "/article"],
	"article.post_article": ["POST", "/article"],
	"article.put_article": ["PUT", "/article"],
	"article.delete_article_id": ["DELETE", "/article/{id}"],
};