/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * test openapi - version 1.0.0
 *
 * 测试交互文档
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
/*export default {
	"login.get_login_current_user": ["GET", "/login/current-user"],
	"login.get_login_get_menus": ["GET", "/login/get-menus"],
	"login.post_login_auth_login": ["POST", "/login/auth-login"],
	"schedule.post_schedule_appointment": ["POST", "/app/sCenter/lesson/appoint"],
	"schedule.get_schedule_query": ["GET", "/app/sCenter/lesson/list"],
	"schedule.post_schedule_leave": ["POST", "/app/sCenter/lesson/leave"],
	"schedule.post_schedule_sign_in": ["POST", "/app/sCenter/lesson/sign/{lessonId}"],
	"me.get_me_manual_getList": ["GET", "/me/manual/getList"],
	"me.get_me_manual_getDetail": ["GET", "/me/manual/getDetail"],
	"me.put_me_modify_name": ["PUT", "/me/modify-name"],
	"me.put_me_modify_password": ["PUT", "/me/modify-password"],
	"me.get_me_getOptionalGrade": ["GET", "/me/getOptionalGrade"],
	"me.get_me_getMyPoint": ["GET", "/me/getMyPoint"],
	"me.get_me_removeStudent": ["GET", "/me/removeStudent"],
	"me.get_me_currentStudentQueryOne": ["GET", "/me/currentStudentQueryOne"],
	"me.post_me_addStudent": ["POST", "/me/addStudent"],
	"me.get_me_getStudentList": ["GET", "/me/getStudentList"],
	"me.get_me_switchStudent": ["GET", "/me/switchStudent"],
	"sCenter.get_app_sCenter_advertisement": ["GET", "/app/sCenter/advertisement"],
	"sCenter.get_app_sCenter_advertisementList": ["GET", "/app/sCenter/advertisementList"],
	"sCenter.get_app_sCenter_student_redpoint": ["GET", "/app/sCenter/student/redpoint"],
	"home.get_home_attendance_records_page_query_by_student_id": ["GET", "/app/sCenter/lesson/signRecord"],
	"home.post_home_attendance_records_evaluate": ["POST", "/app/sCenter/lesson/teachEvaluate"],
	"home.get_home_class_info_query_by_class_id": ["GET", "/app/sCenter/class/info"],
	"home.get_home_class_page_query_by_student_id": ["GET", "/app/sCenter/class/list"],
	"home.get_home_class_student_list_query_by_class_id": ["GET", "/app/sCenter/student/studentList"],
	"home.get_c1_home_card_list": ["GET", "/app/sCenter/course/trialList"],
	"home.get_app_sCenter_course_myTrialList": ["GET", "/app/sCenter/course/myTrialList"],
	"home.get_c1_home_card_rule": ["GET", "/app/sCenter/course/getRule"],
	"home.put_c1_card_put": ["PUT", "/app/sCenter/course/catchTrial/{trialId}"],
	"home.get_c1_exchange_query_allGoods": ["GET", "/app/sCenter/credit/list"],
	"home.get_c1_exchange_goods_detail_id": ["GET", "/app/sCenter/credit/info"],
	"home.get_c1_exchange_query_acceptGoods": ["GET", "/app/sCenter/credit/exchangeRecord"],
	"home.get_c1_exchange_query_rule": ["GET", "/app/sCenter/credit/getRule"],
	"home.post_c1_exchange_submit": ["POST", "/app/sCenter/credit/exchange"],
	"home.get_c1_registration_records_query_records": ["GET", "/app/sCenter/shop/courseInfo"],
	"home.get_c1_review_records_query_reviews": ["GET", "/app/sCenter/lesson/evaluateLog"],
	"home.get_c1_home_score_query_score_list": ["GET", "/app/sCenter/student/gradeRecord"],
	"home.get_c1_homework": ["GET", "/app/sCenter/homework/list"],
	"home.get_c1_homework_detail": ["GET", "/app/sCenter/homework/info"],
	"home.post_c1_homework_submit": ["POST", "/app/sCenter/homework/saveRecord"],
	"home.delete_c1_homework_delete": ["DELETE", "/app/sCenter/homework/deleteRecord/{id}"],
	"article.get_article": ["GET", "/article"],
	"article.post_article": ["POST", "/article"],
	"article.put_article": ["PUT", "/article"],
	"article.delete_article_id": ["DELETE", "/article/{id}"],
};
*/
export default {
    // 原有的 login（保留）
    "login.get_login_current_user": ["GET", "/login/current-user"],
    "login.get_login_get_menus": ["GET", "/login/get-menus"],
    "login.post_login_auth_login": ["POST", "/login/auth-login"],
    "login.get_login_logout": ["GET", "/login/logout"],
    "login.post_login_reset_password": ["POST", "/login/reset-password"],

    // schedule 模块（部分路径已更新）
    "schedule.post_schedule_appointment": ["POST", "/c1schedule/sCenter/lesson/appoint"],
    "schedule.get_schedule_query": ["GET", "/c1schedule/sCenter/lesson/list"],
    "schedule.post_schedule_leave": ["POST", "/c1schedule/sCenter/lesson/leave"],
    "schedule.post_schedule_sign_in": ["POST", "/c1schedule/sCenter/lesson/sign/{lessonId}"],

    // me 模块（保留原有）
    "me.get_me_manual_getList": ["GET", "/me/manual/getList"],
    "me.get_me_manual_getDetail": ["GET", "/me/manual/getDetail"],
    "me.get_me_get_parentinfo": ["GET", "/me/get-parentinfo"],
    "me.put_me_modify_name": ["PUT", "/me/modify-name"],
    "me.put_me_modify_password": ["PUT", "/me/modify-password"],
    "me.get_me_getOptionalGrade": ["GET", "/me/getOptionalGrade"],
    "me.get_me_getMyPoint": ["GET", "/me/getMyPoint"],
    "me.get_me_removeStudent": ["GET", "/me/removeStudent"],
    "me.get_me_currentStudentQueryOne": ["GET", "/me/currentStudentQueryOne"],
    "me.post_me_addStudent": ["POST", "/me/addStudent"],
    "me.get_me_getStudentList": ["GET", "/me/getStudentList"],
    "me.get_me_switchStudent": ["GET", "/me/switchStudent"],

    // sCenter 模块（保留原有）
    "sCenter.get_app_sCenter_advertisement": ["GET", "/app/sCenter/advertisement"],
    "sCenter.get_app_sCenter_advertisementList": ["GET", "/app/sCenter/advertisementList"],
    "sCenter.get_app_sCenter_student_redpoint": ["GET", "/app/sCenter/student/redpoint"],

    // home 模块（已按新路径更新或保留原有对应）
    "home.get_home_attendance_records_page_query_by_student_id": ["GET", "/app/sCenter/lesson/signRecord"],
    "home.post_home_attendance_records_evaluate": ["POST", "/app/sCenter/lesson/teachEvaluate"],
    "home.get_home_class_info_query_by_class_id": ["GET", "/app/sCenter/class/info"],
    "home.get_home_class_page_query_by_student_id": ["GET", "/app/sCenter/class/list"],
    "home.get_home_class_student_list_query_by_class_id": ["GET", "/app/sCenter/student/studentList"],
    "home.get_c1_exchange_query_allGoods": ["GET", "/app/sCenter/credit/list"],
    "home.get_c1_exchange_goods_detail_id": ["GET", "/app/sCenter/credit/info"],
    "home.get_c1_exchange_query_acceptGoods": ["GET", "/app/sCenter/credit/exchangeRecord"],
    "home.get_c1_exchange_query_rule": ["GET", "/app/sCenter/credit/getRule"],
    "home.post_c1_exchange_submit": ["POST", "/app/sCenter/credit/exchange"],
    "home.get_c1_registration_records_query_records": ["GET", "/app/sCenter/shop/courseInfo"],
    "home.get_c1_review_records_query_reviews": ["GET", "/app/sCenter/lesson/evaluateLog"],
    "home.get_c1_home_score_query_score_list": ["GET", "/app/sCenter/student/gradeRecord"],
    "home.get_c1_homework": ["GET", "/app/sCenter/homework/list"],
    "home.get_c1_homework_detail": ["GET", "/app/sCenter/homework/info"],
    "home.post_c1_homework_submit": ["POST", "/app/sCenter/homework/saveRecord"],
    "home.delete_c1_homework_delete": ["DELETE", "/app/sCenter/homework/deleteRecord"],

    // 公告提醒模块
    "home.get_app_sCenter_advertisement": ["GET", "/app/sCenter/advertisement"],
    "home.get_app_sCenter_advertisementList": ["GET", "/app/sCenter/advertisementList"],

    // 小红点提醒模块
    "home.get_app_sCenter_student_redpoint": ["GET", "/app/sCenter/student/redpoint"],

    // 机构管理模块
    "institution.get_c2_org_institution_getInstitutionTree": ["GET", "/c2-org/institution/getInstitutionTree"],

    // 试听卡模块
    "home.get_c1_home_card_list": ["GET", "/app/sCenter/course/trialList"],
    "home.get_app_sCenter_course_myTrialList": ["GET", "/app/sCenter/course/myTrialList"],
    "home.get_c1_home_card_rule": ["GET", "/app/sCenter/course/getRule"],
    "home.put_c1_card_put": ["PUT", "/app/sCenter/course/catchTrial/{trialId}"],

    // article 模块（保留原有）
    "article.get_article": ["GET", "/article"],
    "article.post_article": ["POST", "/article"],
    "article.put_article": ["PUT", "/article"],
    "article.delete_article_id": ["DELETE", "/article/{id}"],


};